### ISSUE TITLE
Add Install OFW option (like NightFall)

### ISSUE THREAD

**Issue by tatundria** [HamletDuFromage/AIO-switch-updater#1]
Please, add the option to install the downloaded OFW from the app (like NightFall app). Is that possible?

**Comment by HamletDuFromage** [comment]
You mean installing firmware? What's wrong with DayBreak/ChoiDuJourNx?

**Comment by tatundria** [comment]
Since it's an AOI it would be great to have the option to download and install from the same app.

Also, it is possible to show OFW and AMS versions info inside the app?

**Comment by HamletDuFromage** [comment]
I could just take daybreak's code and implement it but at the end of the day you'd have a solution that would always be lagging behind daybreak + that's not a responsibility I'm willing to take

I can and will show FW version, but probably not AMS since it's one of the CFW that are supported. You could just look it up in system settings though

**Comment by tatundria** [comment]
You can always take NightFall code:

https://github.com/D3fau4/NightFall

**Comment by D3fau4** [comment]
yo wtf

**Comment by HamletDuFromage** [comment]
@D3fau4 don't worry, not doing that

**Comment by laurinneff** [comment]
I don't know if this would be possible with switch homebrew, but maybe ChoidujourNX (and other FW updaters) could add an API to pass firmware files in the arguments, and then this could add an option to launch a FW updater with these arguments and then the issue of lagging behind updates of the updater would be fixed
