### ISSUE TITLE
having issues when i try to enter my email address in cheatslips on switch

### ISSUE THREAD

**Issue by pompanu** [HamletDuFromage/aio-switch-updater#112]
hi so i hold R in a game and enter ASU then when i enter my email address i hit ok or the + key and it says "the page could not be displayed due to an error" i cant even enter my password. when i look at this photo it say submit which im not seeing.
![Screenshot_109](https://user-images.githubusercontent.com/87625514/126090297-48772448-861e-4871-a6ed-385f0940830a.png)
this is what i get after i enter my email. im not sure if im doing anything wrong. thanks for your help

![](https://cdn.discordapp.com/attachments/851466452959494234/851470530912976906/image0.jpg)

![](https://cdn.discordapp.com/attachments/851466452959494234/851632863837159474/image1.jpg)

**Comment by HamletDuFromage** [comment]
So that's the web browser (and cheatslips.com text shouldn't be there, it's a bad copy paste). Are you sure you're clicking on this entry?
![2021071922205400-AA71E2AFC9F7F9E5FD09714F8D1FBAE7](https://user-images.githubusercontent.com/61667930/126221775-a7156753-e508-44f6-82b9-ec24e9fdbb69.jpg)

If you are and it still doesn't work, try with with this .nro
[aio-switch-updater.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6843705/aio-switch-updater.zip)

and if somehow that fails you can get your token directly from cheatslips
[token.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6843725/token.zip)

**Comment by pompanu** [comment]
says "could not fetch selected cheat codes/invalid token" will it work if i put those 2 files you sent on my sd card?

**Comment by HamletDuFromage** [comment]
It looks like your token is wrong. Get it from here https://www.cheatslips.com/profile/api, paste in token.json and place token.js in config/aio-switch-updater

**Comment by pompanu** [comment]
i just tried that but still getting that same message. "could not fetch selected cheat codes/invalid token" im not sure what else to do. also you make a new folder called config right? i tried both putting it in config and not

**Comment by HamletDuFromage** [comment]
![image](https://user-images.githubusercontent.com/61667930/126501181-a5b72ef1-05cd-4da7-96b5-fd7585ed6f20.png)
Your layout should look something like this. Do you have token.json file in config/aio-switch-updater? If so does it contain the same token as the one you can find in  https://www.cheatslips.com/profile/api?

**Comment by pompanu** [comment]
TYVM it works now I really really appreciate your help=) thanks again

**Comment by HamletDuFromage** [comment]
I'm glad :)
