### ISSUE TITLE
'Download and extract the entire GBAtemp cheats archive' doesn't work

### ISSUE THREAD

**Issue by ms2048** [HamletDuFromage/aio-switch-updater#163]
**Describe the bug**
When selecting the option to extract the archive, it is redownloaded from the Internet (even if it already exists). Afterwards, the progress bar is shown but only for a fraction of a second. Then, the message 'All done!' appears. Nothing actually gets extracted. Additionally, an option for this extraction when offline would be useful (right now it does not appear when offline).

**To Reproduce**
When online, select Tools -> Cheats menu -> Download and extract the entire GBAtemp cheats archive -> Continue

**Screenshots/Crash code/Crash reports**
n/a

**System Firmware Version and CFW Version**
 - System Firmware: 13.1.0
 - CFW Version: Atmosphère 1.2.4
 - AIO Version: 2.16.1

**SD card format**
FAT32

**Additional context**
n/a

**Comment by ms2048** [comment]
Confirmed working. Minor details:
- the progress bar starts at 22% for some reason
- it is only extracting some of the files (the ones that can actually work, which is a fine choice); there are also folders in the archive with 15 and 17 digits, also files outside of the 'cheats' folders - both kinds are ignored; this is not documented anywhere though
- when offline, extraction works just fine, but the use of the 'download' word in the offline context might be confusing (like I mentioned somewhere else)

Other than that, everything seems perfect. Thank you!

**Comment by HamletDuFromage** [comment]
- Progress bar starting at 22% simply means that cheat codes weren't found for the first 22% of games checked. It depends on the games you own.
- For the wrongly named folders the best thing to do is inform Matias3ds on gbatemp about it. I've done it before and he usually fixes it fast. Wrongly formated files are not extracted since my program can't tell which game their for or if they're actual cheat files. What kind of documentation do you have in mind?
- offline behavior really is an afterthought, it's unlikely I'll change strings
