### ISSUE TITLE
Check free space before downloading 

### ISSUE THREAD

**Issue by rashevskyv** [HamletDuFromage/aio-switch-updater#226]
At the moment, the program checks if there is free space to download files, but does not check if there is enough space to unpack them. Ideally, the program should not download files if there is no space on the card to unpack them. That is, for a successful download, you need 2.5 times more free space than the file size.

**Comment by HamletDuFromage** [comment]
It checks before extraction: 
https://github.com/HamletDuFromage/aio-switch-updater/blob/master/source/extract.cpp#L93
https://github.com/HamletDuFromage/aio-switch-updater/blob/master/source/extract.cpp#L237

It does not check for size before before a download however. By retrieving headers before downloading, we could get the size and check before downloading. I'll keep this issue open because I might implement that

**Comment by HamletDuFromage** [comment]
Actually I'm wrong, there is a check for size before downloading. It checks that there is 110% of the expected size available, and then another check occurs before extraction. I guess I could make it so that the first check expects 250%

**Comment by HamletDuFromage** [comment]
done

**Comment by rashevskyv** [comment]
Thank you!
