### ISSUE TITLE
support GitHub releases for custom download

### ISSUE THREAD

**Issue by raulvasquez** [HamletDuFromage/aio-switch-updater#250]
**What feature are you suggesting?**
Add an option to save a GitHub page custom downloads so the latest release zip can be fetched.

Either https://github.com/author/project or https://github.com/author/project/releases/

**Additional context**
I tried to add a direct link to a gh release zip, but couldn't fit the full link due to the character limit on custom downloads.

**Comment by HamletDuFromage** [comment]
[aio-switch-updater.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/11410698/aio-switch-updater.zip)

I increased the max string length to 256. This should cover your use case now. Feel free to use the version I just attached because I'm probably not gonna release a new version for a while
