### ISSUE TITLE
Update in app : 2.1.1 downloaded but not used

### ISSUE THREAD

**Issue by Draky50110** [HamletDuFromage/aio-switch-updater#45]
Hello.

Launching 2.1.0, it tells me there is an update.
I launch the download, but after it relaunch the 2.1.0 and not the 2.1.1 :/ 

Also, why in the ZIP ther eare 2 .nro ? One small and one big.

**Comment by HamletDuFromage** [comment]
yup sorry, i fucked up a little there. 2.1.1 was downloaded, but I compiled it with the 2.1.0 version tag, hence the identity crisis. This is fixed now, you can download it again. 

The reason there are two nros is because I used to have a different way of updating the app, and it needed a *-v.x.x.x.nro filename in order to work. Now I cleaned it up, but I'm keeping the other nro for compatibility. The *-v.x.x.x.nro just launches the normal .nro
